# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18uzANhoodwwX32ro6xrWeov2Vqq1-PNc
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

BaseDados = pd.read_excel("Dados_Pib.xlsx")

print(BaseDados.head())

Grafico = sns.FacetGrid(BaseDados, col="Territorialidades", hue="Territorialidades", col_wrap=4)
Grafico = Grafico.map(plt.plot, "Ano", "PIB per capita")
Grafico = Grafico.map(plt.fill_between,  'Ano', 'PIB per capita', alpha=0.2).set_titles('{col_name} Territorialidades')
Grafico = Grafico.set_titles('{col_name}')
Grafico = Grafico.fig.suptitle(
    'Evolução da Renda per capita por Estado',
    fontsize=18
)

plt.subplots_adjust( top=0.92 )

plt.show()
